name: jobs examples

on:
   push

jobs:
  job1:
   build:
   deploy:
    runs-on: ubuntu-latest
      needs: build
    steps:
      - name: step do job1
        run: echo Hello, world! job1.


  job2:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step do job2
        run: echo Hello, world! Job2.
